### ISSUE TITLE
Feature Implementations

### ISSUE THREAD

**Issue by ToJen** [superbitcoin/SuperBitcoin#17]
The [website](http://supersmartbitcoin.com/) mentions the use of smart contracts as well as other important features like ZK-proofs. Where are the implementations in the repository?

**Comment by rangershi** [comment]
We will probably implement the smart contract around April next year. 
we will be Real time open source.
Thank you for your attention

**Comment by songnob** [comment]
Did mainnet launch?

**Comment by rangershi** [comment]
@songnob the mainnet lauched  ,but only forked  , many functions are coming.
