### ISSUE TITLE
Wallet nodes

### ISSUE THREAD

**Issue by calavander** [superbitcoin/SuperBitcoin#22]
Are there any nodes that can be added to the config file of the wallet for more connections? The core wallet takes very long to sync the network.

**Comment by superbitcoin** [comment]
try those nodes 
connect=120.27.17.34:8334
connect=120.78.188.194:8334
connect=118.31.46.190:8334
connect=101.132.176.152:8334

**Comment by calavander** [comment]
Thank you very much for the response. 1 of them I think is connecting, but I still have 9 days to sync my wallet. If more connections are available please let me know. Thanks again!

**Comment by mathabu** [comment]
hi where can i put the nodes? is in wallet setting > network> proxy ip.
is that correct?

**Comment by rangershi** [comment]
@mathabu  in sbtc.conf  file

**Comment by cyberwitch** [comment]
My client can't connect to any of these nodes, are they still live?

**Comment by harryge00** [comment]
can I mine SBTC using this wallet?

**Comment by mathabu** [comment]
yes for sure
