### ISSUE TITLE
Cannot import a wallet / private keys

### ISSUE THREAD

**Issue by sandoche** [superbitcoin/SuperBitcoin#28]
I am using the SBTC wallet on windows and I don't see any "import a wallet" or "import private keys" option. How can I do that?

**Comment by rangershi** [comment]
This is a Advanced features  not suport by UI ， you can import   private keys by RPC command

**Comment by sandoche** [comment]
Can you explain how to do it and add it to the documentation?

**Comment by sandoche** [comment]
I just found this:
https://bitcoin.stackexchange.com/questions/5941/how-do-i-import-a-private-key-into-bitcoin-qt

I'll give a try, it will take some time to sync the full node though.

**Comment by Miranet** [comment]
Yo sandoche! Any luck so far?

**Comment by sandoche** [comment]
I am still syncing the full blockchain it will take a few more days (and my internet connection is also bad) but the private key importation seemed to work.

**Comment by Krumklash** [comment]
Hey! Has anyone managed to get like SuperBitcoins?

**Comment by msncrkl** [comment]
i am using ZEBPAY and Coin.ph how i get Private Key

**Comment by fabrizioq83** [comment]
i uploaded my wallet.dat file manually in their folder...I not see any sbtc balance..I think that sbtc is only fake coin

**Comment by fabrizioq83** [comment]
ok..i received my sbtc importing my private key on bither and transfer sbtc on bitpie address. Your core wallet have some problem to show correct balance.

**Comment by LeaTex** [comment]
@rangershi I can't import segwit addresses (starting with 3) using the importprivkey command.
no probleman with the old format (starting with 1).
