### ISSUE TITLE
why no bitcoin-qt for Linux (Ubuntu) ?

### ISSUE THREAD

**Issue by magus777** [superbitcoin/SuperBitcoin#34]
Please provide the bitcoin-qt for Linux (Ubuntu)

**Comment by magus777** [comment]
I got bored of waiting, so I installed Wine on Ubuntu and used the Windows bitcoin-qt.exe
It works!

**Comment by superbitcoin** [comment]
wei  will drop the bitcoin-qt, instaed will a web wallet

**Comment by Kandy-Ye** [comment]
Is there a document for building code?

**Comment by SteveSether** [comment]
The QT version for linux builds and runs just fine.  Compiling is quite straightforward if you follow the instructions for the Unix build inside the doc directory.

I strongly think you should re-consider dropping support for the QT version.  Bitcoin need high security, and web browsers are never going to provide the kind of security needed.  The attack surface of a web browser is extremely high.

**Comment by learnforpractice** [comment]
Hmm, sounds like it’s waste of time
