### ISSUE TITLE
Support for bech32 address?

### ISSUE THREAD

**Issue by vachichuong** [superbitcoin/SuperBitcoin#35]
do it support bech32 address right now? if not , will it?

**Comment by FieserKiller** [comment]
I too second bech32 support

**Comment by darthginger** [comment]
I tried to import my private keys (Starting with an L) from my bech32 electrum wallet to claim my sbtc but it just says: Invalid private key encoding (code -5)

**Comment by LeaTex** [comment]
I have the same issue with segwit addresses, starting with 3.
