### ISSUE TITLE
signation not correct

### ISSUE THREAD

**Issue by bitcodernull** [superbitcoin/SuperBitcoin#37]
#### If so, please list the steps to reproduce below:

i sign the transaction by bitcoinjs-lib
i followed the document , but not correct
the code :
`
writeUInt32(this.locktime)
   writeUInt32(hashType)
    writeUInt8(4)   //the length of "sbtc"
    writeSlice( Buffer.from("sbtc"))  //"sbtc"
  return bcrypto.hash256(tbuffer)
`

when i  send transaction , i got the errors:
`{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"}`

what wrong about it

**Comment by posuda** [comment]
From my light wallet app:
{"result":null,"error":{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"},"id":1}

From node:
![sbtc-wallet-08-01-2018](https://user-images.githubusercontent.com/14328865/34666030-7c2ddef8-f473-11e7-9000-61faff6e2794.png)

**Comment by bitcodernull** [comment]
I met the same errors

**Comment by Ben002** [comment]
https://github.com/superbitcoin/SuperBitcoin/blob/master/doc/modification%20on%20SBTC%20signature%20connector.md

![image](https://user-images.githubusercontent.com/20814894/34756258-81877dcc-f604-11e7-8ef3-d40f31b292c1.png)

**Comment by posuda** [comment]
It works for me. Thanks!
