### ISSUE TITLE
blockchain not syncing, stuck at 2015

### ISSUE THREAD

**Issue by sunk818** [superbitcoin/SuperBitcoin#40]
do you have blockchain.zip for us to download?

**Comment by hayzamjs** [comment]
I am not able to sync with any nodes either.. :(

**Comment by Ben002** [comment]
You can synchronize with SBTC wallets.Be careful not to synchronize to the original bitcoins folder, and many people have made this mistake that can't be synchronized.

**Comment by vr4dude316** [comment]
nor can i.  ive started sbtcd -daemon.  i see connections, but no blocks loading
