### ISSUE TITLE
Node Connection

### ISSUE THREAD

**Issue by vr4dude316** [superbitcoin/SuperBitcoin#56]
### Describe the issue

Have core running, syncing now.  Only 3 connections consistently.  Any addnodes I can add to the conf file?

### What version of sbtc-core are you using?
Latest v

**Comment by superbitcoin** [comment]
yes ,sbtc-0.16.2-win.zip

**Comment by superbitcoin** [comment]
try those nodes
connect=120.27.17.34:8334
connect=120.78.188.194:8334
connect=118.31.46.190:8334
connect=101.132.176.152:8334
