### ISSUE TITLE
send signation  Transaction error 

### ISSUE THREAD

**Issue by pzzy2000** [superbitcoin/SuperBitcoin#61]
help ! 
Consult the solution . 

I  signation   super bitcoin  raw Transaction   . send rawtx   by  http://block.superbtc.org/tx/send 。

 i got the errors: 

An error occured:

16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26

Signed   tx   :  020000000117f65df6710b2804862d65d7035a41a27d2d4f81d4e20a99ead50fb3a6c8104e00000000232103e630b80bc91e810e63a39b326b0fc0ef6f1d17f6f7dec0a78af016fca25baad6acffffffff01e8030000000000001976a914d135a2a0ef0135205c44fb857a615be8f301a0b288ac00000000410000000473627463

Signed  Hash  :  7a664815f7150c21ec4f740488c5c01ec98a5cfdf7da98c7c979dc1cfc8cd45a

Signed   sig  :  3045022100d550f800fab2e5590b342c71663ed6d84875976ce6fad945894976ed821bd29a0220191d88a0e88cccf738dfe61a6060d8a5445172bd0f073bb64c443ac053a6ad53

Signed  script - >  483045022100d550f800fab2e5590b342c71663ed6d84875976ce6fad945894976ed821bd29a0220191d88a0e88cccf738dfe61a6060d8a5445172bd0f073bb64c443ac053a6ad53412103e630b80bc91e810e63a39b326b0fc0ef6f1d17f6f7dec0a78af016fca25baad6 

--> txid  75a15ede2687dab54666ace66d2442e66e2efe6a0c71862a3c4c84d04032797e
--> raw  020000000117f65df6710b2804862d65d7035a41a27d2d4f81d4e20a99ead50fb3a6c8104e000000006b483045022100d550f800fab2e5590b342c71663ed6d84875976ce6fad945894976ed821bd29a0220191d88a0e88cccf738dfe61a6060d8a5445172bd0f073bb64c443ac053a6ad53412103e630b80bc91e810e63a39b326b0fc0ef6f1d17f6f7dec0a78af016fca25baad6ffffffff01e8030000000000001976a914d135a2a0ef0135205c44fb857a615be8f301a0b288ac00000000

code : 

       sigHashType = ScriptOpCodes.SIGHASH_ALL|ScriptOpCodes.SIGHASH_FORKID;
      
        txVersion = 2;

        outBuffer.putInt(txVersion);

        //        Serialize the inPutputs
        List<TransactionInput> sigInputs;

        sigInputs = txInputs;

        outBuffer.putVarInt(sigInputs.size());
        
        byte[] emptyScriptBytes = new byte[0];
        
        for (TransactionInput txInput : sigInputs) {
        	
            txInput.serializeForSignatureByForString(index, sigHashType, (txInput.getIndex() == index ? publicKey : emptyScriptBytes), outBuffer);
        }
        //
        // Serialize the outputs
        //
        
        outBuffer.putVarInt(txOutputs.size());
        
        for (TransactionOutput txOutput : txOutputs){
        	
        	  txOutput.serializeForSignature(index, sigHashType, outBuffer);
        	
        }
        //
        // Serialize the lock time and hash type
        //
        outBuffer.putUnsignedInt(txLockTime).putInt(sigHashType);
        
        outBuffer.putBytes(Hex.decode(this.bitCoinType.getForkString()));

        return sigHashType;

Please help ！

**Comment by superbitcoin** [comment]
OK,let's see

**Comment by superbitcoin** [comment]
Currently, this block browser does not support this feature, you may need to synchronize a full node to achieve.Thank you for your attention！

**Comment by pzzy2000** [comment]
thank !
