### ISSUE TITLE
help ! who   provide   superbtc  version  Support  insight-api

### ISSUE THREAD

**Issue by pzzy2000** [superbitcoin/SuperBitcoin#62]
who   provide     superbtc  version  Support  insight-api ?
 
LIKE  http://block.superbtc.org/ 

THK

**Comment by Ben002** [comment]
Blockchain Browser?The third development
sbtc api is here

**Comment by JamT04D** [comment]
The insight explorer doesn't seem to have any parameters set for distribution supply. ie ?=gettotalbc or 
?=getmoneysupply
Is this explorer set up to provide the total and free float supply with an api end-point rather than a calculation on the block height and coinbase tx.
