### ISSUE TITLE
SBTC开发团队就是吃屎的

### ISSUE THREAD

**Issue by yb1991** [superbitcoin/SuperBitcoin#68]
This issue tracker is only for technical issues related to sbtc-core.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of sbtc-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by luxianyou** [comment]
是的，就是吃屎的，而且Ranger Shi(屎）第一个吃屎

**Comment by yb1991** [comment]
对，我赞同




| |
禹宝
邮箱：18512239956@163.com
|

签名由 网易邮箱大师 定制

在2018年07月21日 19:47，陆显友 写道：

是的，就是吃屎的，而且Ranger Shi(屎）第一个吃屎

**Comment by luxianyou** [comment]
因为吃了屎所以失了智，现在团队还想勾结平台低价买回傻逼套餐，哈哈，简直痴人说梦，哪有这么好的事，哈哈。等他们急了，我们温州的搞一个傻逼套餐场外交易，完美抢过来，分裂傻逼套餐，让他妈呢团队继续吃屎我们团队迎头赶上，造福韭菜矿工。

**Comment by luxianyou** [comment]
兄弟，电话泄露了，小心他们电话轰炸，不过报警就行了，轰炸犯法

**Comment by yb1991** [comment]
没事，我不接就好了




| |
禹宝
邮箱：18512239956@163.com
|

签名由 网易邮箱大师 定制

在2018年07月21日 19:52，陆显友 写道：

兄弟，电话泄露了，小心他们电话轰炸，不过报警就行了，轰炸犯法
