### ISSUE TITLE
Stuck Blockchain at block 530554

### ISSUE THREAD

**Issue by tperalta82** [superbitcoin/SuperBitcoin#69]
This issue tracker is only for technical issues related to sbtc-core.

#### If so, please list the steps to reproduce below:
1.  Blockchain won't sync with current 0.17.1 wallet
2.
3.

### Expected behaviour
Tell us what should happen
Blockchain should sync

### Actual behaviour
Tell us what happens instead
Stuck at block 530554

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of sbtc-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
0.17.0.1 
### Machine specs:
- OS: Ubuntu 16.04
- CPU: Xeon D-1521
- RAM: 32GB
- Disk size: 2TB
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
getpeerinfo
[
  {
    "id": 2,
    "addr": "39.104.28.97:8334",
    "addrlocal": "x.x.x.x:33314",
    "addrbind": "x.x.x.x:33314",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206652,
    "lastrecv": 1532206652,
    "bytessent": 4359,
    "bytesrecv": 33235,
    "conntime": 1532204628,
    "timeoffset": 0,
    "pingtime": 1.396431,
    "minping": 0.239358,
    "version": 70017,
    "subver": "/SuperBitcoin:0.17.0.1/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530554,
    "banscore": 0,
    "synced_headers": 530554,
    "synced_blocks": 530554,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 1915,
      "feefilter": 32,
      "getaddr": 24,
      "getheaders": 1053,
      "ping": 544,
      "pong": 544,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 31762,
      "feefilter": 32,
      "headers": 106,
      "ping": 544,
      "pong": 544,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    }
  },
  {
    "id": 3,
    "addr": "47.52.74.193:8334",
    "addrlocal": "x.x.x.x:52756",
    "addrbind": "x.x.x.x:52756",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206597,
    "lastrecv": 1532206561,
    "bytessent": 3183,
    "bytesrecv": 32705,
    "conntime": 1532204880,
    "timeoffset": 0,
    "pingtime": 0.284747,
    "minping": 0.284443,
    "version": 70017,
    "subver": "/SuperBitcoin:0.17.0.1(bitcore)/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530554,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 1920,
      "feefilter": 32,
      "getaddr": 24,
      "ping": 480,
      "pong": 480,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 31457,
      "feefilter": 32,
      "ping": 480,
      "pong": 480,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 142
    }
  },
  {
    "id": 4,
    "addr": "176.9.148.171:8334",
    "addrlocal": "x.x.x.x:60706",
    "addrbind": "x.x.x.x:60706",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206657,
    "lastrecv": 1532206638,
    "bytessent": 2426,
    "bytesrecv": 32677,
    "conntime": 1532205318,
    "timeoffset": 0,
    "pingtime": 0.014332,
    "minping": 0.014332,
    "version": 70016,
    "subver": "/SuperBitcoin:0.16.0.2/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530556,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 1355,
      "feefilter": 32,
      "getaddr": 24,
      "ping": 384,
      "pong": 384,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 30577,
      "feefilter": 32,
      "getheaders": 1053,
      "ping": 384,
      "pong": 384,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    }
  },
  {
    "id": 5,
    "addr": "47.254.203.200:8334",
    "addrlocal": "x.x.x.x:53358",
    "addrbind": "x.x.x.x:53358",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206612,
    "lastrecv": 1532206642,
    "bytessent": 1898,
    "bytesrecv": 31981,
    "conntime": 1532205531,
    "timeoffset": -1,
    "pingtime": 0.230506,
    "minping": 0.229689,
    "version": 70017,
    "subver": "/SuperBitcoin:0.17.0.1/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530554,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 955,
      "feefilter": 32,
      "getaddr": 24,
      "ping": 320,
      "pong": 320,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 31062,
      "feefilter": 32,
      "ping": 320,
      "pong": 320,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    }
  },
  {
    "id": 7,
    "addr": "120.27.17.34:8334",
    "addrlocal": "x.x.x.x:33178",
    "addrbind": "x.x.x.x:33178",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206660,
    "lastrecv": 1532206678,
    "bytessent": 1631,
    "bytesrecv": 32672,
    "conntime": 1532205868,
    "timeoffset": -3,
    "pingtime": 0.299327,
    "minping": 0.299192,
    "version": 70016,
    "subver": "/SuperBitcoin:0.16.0.2/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530556,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 880,
      "feefilter": 32,
      "getaddr": 24,
      "ping": 224,
      "pong": 224,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 30892,
      "feefilter": 32,
      "getheaders": 1053,
      "ping": 224,
      "pong": 224,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    }
  },
  {
    "id": 8,
    "addr": "118.31.46.190:8334",
    "addrlocal": "x.x.x.x:56804",
    "addrbind": "x.x.x.x:56804",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206601,
    "lastrecv": 1532206601,
    "bytessent": 569,
    "bytesrecv": 1870,
    "conntime": 1532206428,
    "timeoffset": -2,
    "pingtime": 7.375374,
    "minping": 7.375374,
    "pingwait": 128.662915,
    "version": 70017,
    "subver": "/SuperBitcoin:0.17.0.1/",
    "inbound": false,
    "addnode": false,
    "startingheight": 530554,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 170,
      "feefilter": 32,
      "getaddr": 24,
      "ping": 64,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 55,
      "feefilter": 32,
      "ping": 32,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    }
  },
  {
    "id": 9,
    "addr": "52.9.142.211:8334",
    "addrlocal": "x.x.x.x:55682",
    "addrbind": "x.x.x.x:55682",
    "services": "000000000000000d",
    "relaytxes": true,
    "lastsend": 1532206644,
    "lastrecv": 1532206676,
    "bytessent": 367,
    "bytesrecv": 33831,
    "conntime": 1532206643,
    "timeoffset": 0,
    "pingtime": 0.157285,
    "minping": 0.157285,
    "version": 70015,
    "subver": "/Satoshi:0.14.1/",
    "inbound": false,
    "addnode": false,
    "startingheight": 532986,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "feefilter": 32,
      "getaddr": 24,
      "ping": 32,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 133
    },
    "bytesrecv_per_msg": {
      "addr": 30082,
      "feefilter": 32,
      "getheaders": 1053,
      "inv": 2360,
      "ping": 32,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 126
    }
  }
]

**Comment by rangershi** [comment]
we are fixing this bug.

**Comment by tperalta82** [comment]
Hey there, i updated to 0.17.3, still not fixed, still saying it's downloading blocks, do we have to wait for more 0.17.3 peers come in?

**Comment by bitcodernull** [comment]
I have updated to 0.17.4. still not fixed
 do we have to wait for more 0.17.4 peers come in?

**Comment by bitcodernull** [comment]
maybe i need to reindex all block?

**Comment by tperalta82** [comment]
@bitcodernull  i'm starting my node with 17.4 as well, let's see if we can get this running

**Comment by tperalta82** [comment]
Node is running, pool is up at sbtc.multipools.club, let's hope it finds blocks now! @rangershi  can we keep this open until a block is found?

**Comment by tperalta82** [comment]
Seems like I am the only node running 17.4 ? 
Also seems like that there's no community support whatsoever for this, have you got any telegram/discord that we could use?
there are only 2 miners mining this now (actually, 2 ASICS), at this difficulty, the blockchain will only move in 15 days or more

**Comment by testtkxxd** [comment]
I have updated to 0.17.5. still not fixed
