### ISSUE TITLE
SBTC内幕曝光，总量并非2100万，而是无上限

### ISSUE THREAD

**Issue by yb1991** [superbitcoin/SuperBitcoin#70]
This issue tracker is only for technical issues related to sbtc-core.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of sbtc-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jeremy16601** [comment]
证据呢

**Comment by rangershi** [comment]
你这个 sx 到顶是在搞什么贵？？
