### ISSUE TITLE
SBTC总量是210亿大家别被骗了，你们可以查看源代码。这三个骗子厉害吧

### ISSUE THREAD

**Issue by yb1991** [superbitcoin/SuperBitcoin#72]
This issue tracker is only for technical issues related to sbtc-core.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of sbtc-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by rangershi** [comment]
你还真是个sb 代码都不会看，在这里扯淡。

**Comment by yb1991** [comment]
妈的，core团队不会看代码吗？屌丝真是搞笑。说话文明点，现在没人给你撑腰




| |
禹宝
邮箱：18512239956@163.com
|

签名由 网易邮箱大师 定制

在2018年07月30日 17:04，ranger 写道：

Closed #72.

**Comment by yb1991** [comment]
你少说话多做事好吗……




| |
禹宝
邮箱：18512239956@163.com
|

签名由 网易邮箱大师 定制

在2018年07月31日 00:00，yb1991 写道：
妈的，core团队不会看代码吗？屌丝真是搞笑。说话文明点，现在没人给你撑腰




| |
禹宝
邮箱：18512239956@163.com
|

签名由 网易邮箱大师 定制

在2018年07月30日 17:04，ranger 写道：

Closed #72.
