### ISSUE TITLE
531806的hash是多少

### ISSUE THREAD

**Issue by bitcodernull** [superbitcoin/SuperBitcoin#73]
注意：
如果您在531806高度之后升级，您可能会在531805 不再向前走，这时您需要调用 reconsiderblock + 531806 hash即可。

但外部浏览器挂了，看不到这个hash

**Comment by rangershi** [comment]
530555  hash
000000000000000055f8cd20e1d42b5f915cb51ee68dad397c1b2ed4242faa52
531806 hash
000000000000000121b88d0db1e924f4c9d249d07fb90c8178f451b62e0ed15f
