### ISSUE TITLE
Updated to .17.5, same error as issue 69 I opened days ago

### ISSUE THREAD

**Issue by tperalta82** [superbitcoin/SuperBitcoin#74]
This issue tracker is only for technical issues related to sbtc-core.

#### If so, please list the steps to reproduce below:
1. Upgrade to 0.17.5
2.
3.

### Expected behaviour
Tell us what should happen
getblocktemplate should show block template to send to miners
### Actual behaviour
Tell us what happens instead
Stuck at downloading blocks again
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of sbtc-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
0.17.5
### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
./sbtc-0.17.5-ubuntu16_04/sbtc-cli -datadir=.data getblocktemplate
error code: -10
error message:
Super Bitcoin is downloading blocks...

There are many problems here
the time that it's taking to find blocks is breaking the blockchain, making it think that it's downloading new blocks
Everyone quit mining this and/or pools not updated , as such the difficulty is too high, it will take ages to find blocks

Please fix, I am going to close the sbtc.multipools.club pool again, check your DAA , if it's bitcoin's, it will only adjust every 2 weeks, and 2 weeks with 2 or 3 blocks, it's goodbye

**Comment by rangershi** [comment]
DAA Is right   ,it is  not bitcoin's

**Comment by tperalta82** [comment]
I think we are having communication issues here

Expected behaviour
Tell us what should happen
getblocktemplate should show block template to send to miners

Actual behaviour
Tell us what happens instead
Stuck at downloading blocks again

*this is not fixed*

**Comment by YassineEraman** [comment]
Hi @rangershi please could you tell us what's the problem ?? there's some of my SBTC stuck at the BlockChain about 5 days now !!

best regards

**Comment by tperalta82** [comment]
@YassineEraman I had to re-download entire blockchain, it's working

**Comment by YassineEraman** [comment]
@tperalta82 ok thanks, so i just have to wait okex until they re-download the blockchain again ??

**Comment by YassineEraman** [comment]
Hi @tperalta82 , why do the pool is still in maintenance mode ?
